# ADVANCED SETS
print('''ADVANCED SETS''')

print('''Sets are unordered collections of unique elements''')
a = set()
a.add(1)
a.add(1)
a.add(2)
a.add(3)
a.add(3)
print("My set a:", a)
b = a.copy()
print("My set b (a.copy()):", b)
b.clear()
print("My set b after .clear:", b)
print("A and b difference: ", a.difference(b), "\n")

a = set([1, 2, 3, 4, 5])
b = set([3, 4, 5, 6, 7])
print("My set a:", a)
print("My set b:", b)
a.difference_update(b)
print("Set a after removing common elements with b (a.difference_update(b)) : ", a)
a.discard(1)
print("My set a after a.discard(1):", a, "\n")

a = set([1, 2, 3, 4, 5])
b = set([3, 4, 5, 6, 7])
print("My set a:", a)
print("My set b:", b)
a.intersection_update(b)
print("My set a after a.intersection_update(b):", a.intersection_update(b), "\n")

a = set([1, 2, 3, 4, 5])
b = set([3, 4, 5, 6, 7])
print("My set a:", a)
print("My set b:", b)
#a.union(b)
a.update(b)
print("My set a after a.update(b) (a = a.union(b)):", a, "\n")

print("My set a:", a)
print("My set b:", b)
print("Have a 0 numbers in b? (a.isdisjoint(b)):", a.isdisjoint(b))
print("Is a superset of b? (a.issuperset(b)):", b.issuperset(a))
print("Non common elements between a and b (a.symmetric_difference(b)):", a.symmetric_difference(b), "\n")

